# Generated by Django 3.2.4 on 2021-07-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210704_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(default='', max_length=1000)),
                ('phone', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
