# Generated by Django 3.2.4 on 2021-07-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.ImageField(default=0, upload_to='')),
                ('update_desc', models.CharField(default='', max_length=50000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
